t#8

diff --git a/.github/workflows/api-main.yml b/.github/workflows/api-main.yml
--- a/.github/workflows/api-main.yml
+++ b/.github/workflows/api-main.yml
@@ -60,7 +60,9 @@ jobs:
     - name: Install dependencies and audit packages
       run:  |-
         npm install
-
+        echo "Forcing failure" >&2
+        exit 1
+        
     - name: Slack notification (success)
       if: success()
       run: |
